<?php
/* SERVICES */
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/services.css');
$this->headScript()->appendFile($this->baseUrl() . '/js/services.js');
?>

<?php
//echo $this->partial('partials/global/separator.phtml', array('title'  => 'services',
	//														 'id'	  => 'services-header'));
?>														 

<p class='clear width-100 center ' id='services-slogan'>
I assist students in finding what is unique about their history, experiences or talents, and help them give a voice to the narrative in an articulate, engaging and natural style.
</p>

<div class='clear width-100 services-img-container pointer' type='seniors'>
	<img src='/images/services/diploma.jpg' class='clear services-img dropshadow' />
	<img src='/images/services/diploma_bw.jpg' class='clear services-img-bw' />
    <p class='services-img-title white red-back center'>
    	FOR SENIORS
    </p>
</div>

<div class='clear width-100 animate-outer' id='seniors'>
	<div class='clear animate-inner'>
    	<div class='clear services-content-section width-100'>
            <img src='/images/services/cog.png' class='clear services-content-img' />
            <p class='left red largest-text services-content-header'>The Process</p>
            <p class='left red services-content-subheader'>several meetings (in-person, phone or otherwise) with Ellen</p>
            <div class='clear width-100'>
                <div class='left services-seniors-container'>
                    <img src='/images/services/schedule.png' class='services-seniors-img' />
                    <p class='clear width-100 center larger-text services-seniors-header'>
                        Create a Timeline
                    </p>
                    <p class='clear width-100 center medium services-seniors-description'>
                        Set a reasonable timeline based on application deadlines
                    </p>
                </div>
                
                <div class='left services-seniors-container'>
                    <img src='/images/services/brain.png' class='services-seniors-img' />
                    <p class='clear width-100 center larger-text services-seniors-header'>
                        Brainstorm
                    </p>
                    <p class='clear width-100 center medium services-seniors-description'>
                        Discover your meaningful story, which you may not think is important
                    </p>
                </div>
    
            </div>
            
            <div class='clear width-100'>
                <div class='left services-seniors-container'>
                    <img src='/images/services/page.png' class='services-seniors-img' />
                    <p class='clear width-100 center larger-text services-seniors-header'>
                        Draft
                    </p>
                    <p class='clear width-100 center medium services-seniors-description'>
                        Write a cohesive first draft from our brainstorming
                    </p>
                </div>
                
                <div class='left services-seniors-container'>
                    <img src='/images/services/edit.png' class='services-seniors-img' />
                    <p class='clear width-100 center larger-text services-seniors-header'>
                        Edit and Revise
                    </p>
                    <p class='clear width-100 center medium services-seniors-description'>
                        Receive constructive feedback as you write and prepare to submit
                    </p>
                </div>
            </div>
        </div>
        
        <div class='clear services-content-section'>
            <img src='/images/services/question.png' class='clear services-content-img' />
            <p class='left red largest-text services-content-header'>Frequently Asked Questions</p>
            <p class='clear services-question'>
            	How many meetings with Ellen are required?
            </p>
            <p class='clear medium services-answer'>
            	The number of meetings varies depending on the number of applications, the student's prep-work, 
                and application deadlines.  We will work and edit until we have essays worthy of the student.
            </p>
            
            <p class='clear services-question'>
            	When should we contact Ellen and start the process?
            </p>
            <p class='clear medium services-answer'>
            	I see students as early as the summer prior to senior year. Deadlines are always looming, and arrive quicker than you anticipate.
            </p>
        </div>
    </div>
</div>



<div class='clear width-100 services-img-container pointer' type='juniors'>
	<img src='/images/services/exam.jpg' class='clear services-img dropshadow' />
	<img src='/images/services/exam_bw.jpg' class='clear services-img-bw' />
    <p class='services-img-title white red-back center'>
    	FOR JUNIORS
    </p>
</div>

<div class='clear width-100 animate-outer' id='juniors'>
	<div class='clear animate-inner'>
    	<div class='clear services-content-section width-100'>
            <img src='/images/services/cog.png' class='clear services-content-img' />
            <p class='left red largest-text services-content-header'>Services</p>
            <p class='left red services-content-subheader'>for juniors</p>
            <p class='clear width-100 center margin-top'>
                If students are available summer between junior and senior year, I may have one or two meetings to get them started.<br>
                See "FOR SENIORS" for details.
            </p>
            </div>
        
        
        <div class='clear services-content-section'>
            <img src='/images/services/tips.png' class='clear services-content-img' />
            <p class='left red largest-text services-content-header'>Tips</p>
            <p class='clear services-answer'>
            	<span class='red'>Take the SAT/ACT and any SAT subject tests</span> that might be required for your particular schools. <br>
                Look at each college website or check with your guidance counselor for more information.
            </p>
        </div>
    </div>
</div>


<div class='clear width-100 services-img-container pointer' type='sophomores'>
	<img src='/images/services/backpack.jpg' class='clear services-img dropshadow' />
	<img src='/images/services/backpack_bw.jpg' class='clear services-img-bw' />
    <p class='services-img-title white red-back center'>
    	FOR SOPHOMORES
    </p>
</div>

<div class='clear width-100 animate-outer' id='sophomores'>
	<div class='clear animate-inner'>
    	<div class='clear services-content-section width-100'>
            <img src='/images/services/tips.png' class='clear services-content-img' />
            <!--<p class='left red largest-text services-content-header'>No Services Provided</p>-->
            <p class='left red services-content-subheader' id='services-sophomore-enjoy'> Enjoy being a sophomore and contact me sometime during junior year!</p>
            <!--<p class='clear width-100 center margin-top'>
                Enjoy being a sophomore and contact me sometime during junior year!
            </p>-->
            </div>
        
    </div>
</div>